### ISSUE TITLE
typescript declaration file

### ISSUE THREAD

**Issue by yagisumi** [necojackarc/extensible-custom-error#1]
*This description was translated by @necojackarc*

Hello. I got here from your Qiita post.
I would be happy if you could add a type declaration file for TypeScript and set it in `package.json`.

I think it should be okay:

```ts
export default class ExtensibleCustomError extends Error {
  constructor(message?: string, error?: Error);
  constructor(error: Error);
}
```

**Comment by necojackarc** [comment]
Thanks for the suggestion and sorry for a late reply.

I just merged the PR to resolve this issue and published a new version!
Hope you find it useful.

Cheers.

**Comment by necojackarc** [comment]
@yagisumi Thanks for the suggestion and sorry for a late reply.

I just merged the PR to resolve this issue and published a new version!
Hope you find it useful.

Cheers.
